Table spending_raw {
  "City" varchar
  "Date" varchar
  "Card Type" varchar
  "Exp Type" varchar
  "Gender" varchar
  "Amount" varchar
}

Table unemployment_raw {
  "Region" varchar [note: "Region of the country"]
  "Date" varchar [note: "Month of the record"]
  "Frequency" varchar
  "Estimated Unemployment Rate (%)" varchar
  "Estimated Employed" varchar
  "Estimated Labour Participation Rate (%)" varchar
  "Area" varchar
}

Table spending {
  "State" varchar [note: "Original Region column"]
  "Month" varchar [note: "First day of original Date column"]
  "Amount ($)" varchar
}

Table unemployment {
  "State" varchar [note: "State"]
  "Month" varchar [note: "First day of month of the record"]
  "Unemployment Rate (%)" varchar
}

Table dim_state {
  "State" varchar
}

Table dim_date {
  "Month" varchar
}

ref: spending.Month > dim_date.Month
ref: unemployment.Month > dim_date.Month

ref: spending.State > dim_state.State
ref: unemployment.State > dim_state.State